github.com:
    users:
        logno-dev:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: logno-dev
