# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"github" = ""
"rust" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"chromium" = ""
"thorium-browser" = ""
"brave" = ""
"file manager" = ""
"nautilus" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"onlyoffice" = ""
"nvim" = ""
"gthumb" = ""
"menu" = ""
"calculator" = ""
"transmission" = ""
# "videostream" = ""
# "mpv" = ""
"music" = ""
"disk usage" = ""
"kitty" = ""
# ".pdf" = ""
"gimp" = ""
"discord" = ""
"parsec" = "󱊪"

[other]
fallback_icon = ""
deduplicate_icons = false
separator = ":"
